In [2]:
import pandas as pd
import numpy as np
import math

import matplotlib.pyplot as plt

# Algoritmo de Deutsh

In [5]:
M_a = np.array([[1, 1], [0, 0]])
M_b = np.array([[1, 0], [0, 1]])
M_c = np.array([[0, 1], [1, 0]])
M_d = np.array([[0, 0], [1, 1]])

b0 = np.array([1, 0])
b1 = np.array([0, 1])

print('Primer funcion: \n', M_a @ b0, ' ', M_a @ b1, '\n\n')
print('Segunda funcion: \n', M_b @ b0, ' ', M_b @ b1, '\n\n')
print('Tercera funcion: \n', M_c @ b0, ' ', M_c @ b1, '\n\n')
print('Cuarta funcion: \n', M_d @ b0, ' ', M_d @ b1, '\n\n')

Primer funcion: 
 [1 0]   [1 0] 


Segunda funcion: 
 [1 0]   [0 1] 


Tercera funcion: 
 [0 1]   [1 0] 


Cuarta funcion: 
 [0 1]   [0 1] 




In [7]:
N = np.array([[0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
N_adj = np.matrix(N).getH()
print(N_adj)
print(N @ N_adj)

[[0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
