In [1]:
import pandas as pd
import numpy as np
import math

import matplotlib.pyplot as plt

# Bits y Qubits

In [2]:
V =  np.array([15 - 3.4j, 2.1 - 16j])
V_n = np.linalg.norm(V)
V_norm = V / V_n

print('V normalizado: ', V_norm, '\n')

V normalizado:  [0.67286226-0.15251545j 0.09420072-0.71771975j] 



# Compuertas

In [3]:
NOT = np.array([[0, 1], [1, 0]])
OR = np.array([[1, 0, 0, 0], [0, 1, 1, 1]])

NOT_TENSOR_NOT = np.array([[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0]])
producto = NOT @ OR @ NOT_TENSOR_NOT

print('Compuerta: \n', producto, '\n')

#OPERADOR NO-CONTROLADO
N_C = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
print('Inverso de no-controlado: \n', N_C @ N_C, '\n')

Compuerta: 
 [[1 1 1 0]
 [0 0 0 1]] 

Inverso de no-controlado: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 



# Matrices cuanticas

In [6]:
sigma_x = np.array([[0, 1], [1, 0]])
sigma_y = np.array([[0, -1j], [1j, 0]])
sigma_z = np.array([[1, 0], [0, -1]])

S = np.array([[1, 0], [0, 1j]])
T = np.array([[1, 0], [0, np.exp(1j * np.pi / 4)]])

M_prueba = np.array([[5, 5], [5, 10]])

for M in [sigma_x, sigma_y, sigma_z, S, T]:
    
    efecto_M = M @ M_prueba
    print('Matriz unitaria: \n', M, '\n', M @ np.matrix(M).getH(), '\n')
    print('Efecto: \n', efecto_M, '\n')


Matriz unitaria: 
 [[0 1]
 [1 0]] 
 [[1 0]
 [0 1]] 

Efecto: 
 [[ 5 10]
 [ 5  5]] 

Matriz unitaria: 
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]] 
 [[ 1.+0.j -0.+0.j]
 [-0.+0.j  1.+0.j]] 

Efecto: 
 [[0. -5.j 0.-10.j]
 [0. +5.j 0. +5.j]] 

Matriz unitaria: 
 [[ 1  0]
 [ 0 -1]] 
 [[1 0]
 [0 1]] 

Efecto: 
 [[  5   5]
 [ -5 -10]] 

Matriz unitaria: 
 [[1.+0.j 0.+0.j]
 [0.+0.j 0.+1.j]] 
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]] 

Efecto: 
 [[5. +0.j 5. +0.j]
 [0. +5.j 0.+10.j]] 

Matriz unitaria: 
 [[1.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.70710678+0.70710678j]] 
 [[1.+0.00000000e+00j 0.+0.00000000e+00j]
 [0.+0.00000000e+00j 1.+1.01465364e-17j]] 

Efecto: 
 [[5.        +0.j         5.        +0.j        ]
 [3.53553391+3.53553391j 7.07106781+7.07106781j]] 



In [15]:
#PROBAR OPERACIONES
print('Comprovar relacion')
print(sigma_x @ sigma_x)
print(sigma_y @ sigma_y)
print(sigma_z @ sigma_z)

H = 2**-0.5 * (sigma_x + sigma_z)
print('Matriz H: \n', H, '\n')
print('X = HZH: \n', H @ sigma_z @ H, '\n')
print('Z = HXH: \n', H @ sigma_x @ H, '\n')
print('-1Y = HYH: \n', H @ sigma_y @ H, '\n')
print('S = T*T: \n', T @ T, '\n')
print('-1Y = XYX: \n', sigma_x @ sigma_y @ sigma_x, '\n')

Comprovar relacion
[[1 0]
 [0 1]]
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
[[1 0]
 [0 1]]
Matriz H: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]] 

X = HZH: 
 [[4.26642159e-17 1.00000000e+00]
 [1.00000000e+00 4.26642159e-17]] 

Z = HXH: 
 [[ 1.00000000e+00  4.26642159e-17]
 [-4.26642159e-17 -1.00000000e+00]] 

-1Y = HYH: 
 [[0.+4.26642159e-17j 0.+1.00000000e+00j]
 [0.-1.00000000e+00j 0.-4.26642159e-17j]] 

S = T*T: 
 [[1.00000000e+00+0.j 0.00000000e+00+0.j]
 [0.00000000e+00+0.j 1.79380389e-16+1.j]] 

-1Y = XYX: 
 [[0.+0.j 0.+1.j]
 [0.-1.j 0.+0.j]] 



In [31]:
C_U = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 10, 0], [0, 0, 0, 10]])
Q_0 = np.array([1, 0, 1, 1])
Q_1 = np.array([0, 1, 1, 1])

print('Aplicando C_U: \n', C_U @ Q_0, '\n')
print('Aplicando C_U: \n', C_U @ Q_1, '\n')

Aplicando C_U: 
 [ 1  0 10 10] 

Aplicando C_U: 
 [ 0  1 10 10] 

