In [1]:
import pandas as pd
import numpy as np
import math

import matplotlib.pyplot as plt

# Bits y Qubits

In [4]:
V =  np.array([15 - 3.4j, 2.1 - 16j])
V_n = np.linalg.norm(V)
V_norm = V / V_n

print('V normalizado: ', V_norm, '\n')

V normalizado:  [0.67286226-0.15251545j 0.09420072-0.71771975j] 



# Compuertas

In [8]:
NOT = np.array([[0, 1], [1, 0]])
OR = np.array([[1, 0, 0, 0], [0, 1, 1, 1]])

NOT_TENSOR_NOT = np.array([[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0]])
producto = NOT @ OR @ NOT_TENSOR_NOT

print('Compuerta: \n', producto, '\n')

#OPERADOR NO-CONTROLADO
N_C = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
print('Inverso de no-controlado: \n', N_C @ N_C, '\n')

Compuerta: 
 [[1 1 1 0]
 [0 0 0 1]] 

Inverso de no-controlado: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

