In [2]:
import pandas as pd
import numpy as np
import math

import matplotlib.pyplot as plt

# Sistema deterministico clasico

In [5]:
 M = np.array([[0, 0, 0, 0, 0, 0], 
               [0, 0, 0, 0, 0, 0], 
               [0, 1, 0, 0, 0, 1], 
               [0, 0, 0, 1, 0, 0], 
               [0, 0, 1, 0, 0, 0], 
               [1, 0, 0, 0, 1, 0]])

estado_inicial = np.array([6, 2, 1, 5, 3, 10])

print('Estado inicial: \n', estado_inicial, '\n')
print('Estado despues de 1 clic: \n', M @ estado_inicial, '\n')
print('Estado despues de 2 clic: \n', M @ M @ estado_inicial, '\n')
print('Estado despues de 3 clic: \n', M @ M @ M @ estado_inicial, '\n')
print('Estado despues de 4 clic: \n', M @ M @ M @ M @ estado_inicial, '\n')
print('Estado despues de 5 clic: \n', M @ M @ M @ M @ M @ estado_inicial, '\n')
print('Estado despues de 6 clic: \n', M @ M @ M @ M @ M @ M @ estado_inicial, '\n')

Estado inicial: 
 [ 6  2  1  5  3 10] 

Estado despues de 1 clic: 
 [ 0  0 12  5  1  9] 

Estado despues de 2 clic: 
 [ 0  0  9  5 12  1] 

Estado despues de 3 clic: 
 [ 0  0  1  5  9 12] 

Estado despues de 4 clic: 
 [ 0  0 12  5  1  9] 

Estado despues de 5 clic: 
 [ 0  0  9  5 12  1] 

Estado despues de 6 clic: 
 [ 0  0  1  5  9 12] 



# Sistemas probabilisticos

In [23]:
M = np.array([[0, 1/6, 5/6], [1/3, 1/2, 1/6], [2/3, 1/3, 0]])
X = np.array([1/6, 1/6, 2/3])

print('Estado inicial: \n', X, '\n')

X_1 = M @ X
print('Estado despues de 1 clic: \n', X_1, '\n')
print('Revirtiendo estado: \n', X_1 @ M, '\n')

M = np.array([[1/3, 2/3], [2/3, 1/3]])
N = np.array([[1/2, 1/2], [1/2, 1/2]])
print('Multiplicacion de matrices doble-estocasticas: ', '\n', M @ N, '\n', N @ M, '\n')

A = np.array([[0, 0.5, 0.5, 0], [0.5, 0, 0, 0.5], [0.5, 0, 0, 0.5], [0, 0.5, 0.5, 0]])
estado_inicial = np.array([0, 0.5, 0.5, 0])
print('Estado despues de 1 clic: \n', A @ estado_inicial, '\n')
print('Estado despues de 2 clic: \n', A @ A @ estado_inicial, '\n')
print('Estado despues de 3 clic: \n', A @ A @ A @ estado_inicial, '\n')

Estado inicial: 
 [0.16666667 0.16666667 0.66666667] 

Estado despues de 1 clic: 
 [0.58333333 0.25       0.16666667] 

Revirtiendo estado: 
 [0.19444444 0.27777778 0.52777778] 

Multiplicacion de matrices doble-estocasticas:  
 [[0.5 0.5]
 [0.5 0.5]] 
 [[0.5 0.5]
 [0.5 0.5]] 

Estado despues de 1 clic: 
 [0.5 0.  0.  0.5] 

Estado despues de 2 clic: 
 [0.  0.5 0.5 0. ] 

Estado despues de 3 clic: 
 [0.5 0.  0.  0.5] 



In [37]:
#EXPERIMENTO DE LA DOBLE RENDIJA CON BALAS
B = np.array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
              [0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
              [0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
              [0.0, 1/3, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
              [0.0, 1/3, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
              [0.0, 1/3, 1/3, 0.0, 0.0, 1.0, 0.0, 0.0],
              [0.0, 0.0, 1/3, 0.0, 0.0, 0.0, 1.0, 0.0],
              [0.0, 0.0, 1/3, 0.0, 0.0, 0.0, 0.0, 1.0]])

estado_inicial = np.array([1, 0, 0, 0, 0, 0, 0, 0])

print('Matriz de probabilidades despues de 2 clics: \n', B @ B, '\n')
print('Estado del sistema a partir del inicial y despues de 2 clics: \n', B @ B @ estado_inicial, '\n')

Matriz de probabilidades despues de 2 clics: 
 [[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.16666667 0.33333333 0.         1.         0.         0.
  0.         0.        ]
 [0.16666667 0.33333333 0.         0.         1.         0.
  0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.         0.         1.
  0.         0.        ]
 [0.16666667 0.         0.33333333 0.         0.         0.
  1.         0.        ]
 [0.16666667 0.         0.33333333 0.         0.         0.
  0.         1.        ]] 

Estado del sistema a partir del inicial y despues de 2 clics: 
 [0.         0.         0.         0.16666667 0.16666667 0.33333333
 0.16666667 0.16666667] 



# Sistema Cuantico

In [47]:
U = np.array([[1/2**0.5, 1/2**0.5, 0], [-1j/2**0.5, 1j/2**0.5, 0], [0, 0, 1j]])
U_adj = np.matrix(U).getH()
print('Matriz unitaria: \n', U @ U_adj, '\n', U_adj @ U, '\n')

U_2 = np.abs(U) ** 2
print('Modulos cuadrados (doble estocasticos): \n', U_2, '\n')

B = np.array([[0, 2**-0.5, 2**-0.5, 0], [2**-0.5, 0, 0, -2**-0.5], [2**-0.5, 0, 0, 2**-0.5], [0, -2**0.5, 2**0.5, 0]])
estado_inicial = np.array([1, 0, 0, 0])
print('Bola de billar cuantica: \n', B @ estado_inicial, '\n', B @ B @ estado_inicial, '\n')

Matriz unitaria: 
 [[1.+0.00000000e+00j 0.-2.23711432e-17j 0.+0.00000000e+00j]
 [0.+2.23711432e-17j 1.+0.00000000e+00j 0.+0.00000000e+00j]
 [0.+0.00000000e+00j 0.+0.00000000e+00j 1.+0.00000000e+00j]] 
 [[ 1.00000000e+00+0.j -2.23711432e-17+0.j  0.00000000e+00+0.j]
 [-2.23711432e-17+0.j  1.00000000e+00+0.j  0.00000000e+00+0.j]
 [ 0.00000000e+00+0.j  0.00000000e+00+0.j  1.00000000e+00+0.j]] 

Modulos cuadrados (doble estocasticos): 
 [[0.5 0.5 0. ]
 [0.5 0.5 0. ]
 [0.  0.  1. ]] 

Bola de billar cuantica: 
 [0.         0.70710678 0.70710678 0.        ] 
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -8.53284318e-17] 



In [50]:
#EXPERIMENTO DE LA DOBLE RENDIJA CON FOTONES
P = np.array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
              [2**-0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
              [2**-0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
              [0.0, (-1 + 1j) / 6**0.5, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
              [0.0, (-1 - 1j) / 6**0.5, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
              [0.0, (1 - 1j) / 6**0.5, (-1 + 1j) / 6**0.5, 0.0, 0.0, 1.0, 0.0, 0.0],
              [0.0, 0.0, (-1 - 1j) / 6**0.5, 0.0, 0.0, 0.0, 1.0, 0.0],
              [0.0, 0.0, (1 - 1j) / 6**0.5, 0.0, 0.0, 0.0, 0.0, 1.0]])

estado_inicial = np.array([1, 0, 0, 0, 0, 0, 0, 0])

print('Matriz de modulos al cuadrado: \n', np.abs(P) ** 2, '\n')
P_2 = P @ P
P_2_prob = np.abs(P_2) ** 2 
print('Matriz al cuadrado (probabilidades): \n', P_2_prob, '\n')

Matriz de modulos al cuadrado: 
 [[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.5        0.         0.         0.         0.         0.
  0.         0.        ]
 [0.5        0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.33333333 0.         1.         0.         0.
  0.         0.        ]
 [0.         0.33333333 0.         0.         1.         0.
  0.         0.        ]
 [0.         0.33333333 0.33333333 0.         0.         1.
  0.         0.        ]
 [0.         0.         0.33333333 0.         0.         0.
  1.         0.        ]
 [0.         0.         0.33333333 0.         0.         0.
  0.         1.        ]] 

Matriz al cuadrado (probabilidades): 
 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e