In [1]:
import pandas as pd
import numpy as np
import math

import matplotlib.pyplot as plt

In [2]:
#CONVERT CARTESIAN TO POLAR
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)

def pol2cart(rho, phi):
    x = rho * np.cos(phi)
    y = rho * np.sin(phi)
    return(x, y)

# Operaciones Basicas con Vectores

In [3]:
V = np.array([6j, 8, -1+2j, 4])
W = np.array([14-1J, 0, 4+2j, 3j])

V_0 = np.array([0, 0, 0, 0])

#OPERACIONES BASICAS
print('Suma de vectores: ', V + W)
print('Suma de vectores: ', W + V)
print('Suma con vector cero: ', V, V + V_0)
print('')

#COMPROBAR ESPACIO VECTORIAL COMPLEJO
V = np.array([[5 + 4j, 3 - 2j], [1j, -4 + 2j]])
W = np.array([[0 + 2j, -3 - 2j], [8, -4 - 2j]])
Y = np.array([[1, -3 - 2j], [10j, -4 - 2j]])
Z_0 = np.array([[0, 0], [0, 0]])
c1 = 4 - 2j
c2 = 10 + 2j

print('Conmutatividad de la adición:\n', V + W, '\n', W + V, '\n')
print('Asociatividad de la adición:\n', (V + W) + Y, '\n', V + (W + Y), '\n')
print('Identidad aditiva:\n', V + Z_0, '\n', V, '\n')
print('Inverso aditivo:\n', V + -(V), '\n')
print('Identidad multiplicativa:\n', V, '\n', 1 * V, '\n')
print('Multiplicación escalar:\n', c1 * (c2 * V), '\n', (c1 * c2) * V, '\n')
print('Multiplicación escalar se distribuye sobre adicion:\n', c1 * (V + W), '\n', c1 * V + c1 * W, '\n')
print('Multiplicación escalar se distribuye sobre adicion compleja:\n', (c1 + c2) * V, '\n', c1 * V + c2 * V, '\n')

Suma de vectores:  [14.+5.j  8.+0.j  3.+4.j  4.+3.j]
Suma de vectores:  [14.+5.j  8.+0.j  3.+4.j  4.+3.j]
Suma con vector cero:  [ 0.+6.j  8.+0.j -1.+2.j  4.+0.j] [ 0.+6.j  8.+0.j -1.+2.j  4.+0.j]

Conmutatividad de la adición:
 [[ 5.+6.j  0.-4.j]
 [ 8.+1.j -8.+0.j]] 
 [[ 5.+6.j  0.-4.j]
 [ 8.+1.j -8.+0.j]] 

Asociatividad de la adición:
 [[  6. +6.j  -3. -6.j]
 [  8.+11.j -12. -2.j]] 
 [[  6. +6.j  -3. -6.j]
 [  8.+11.j -12. -2.j]] 

Identidad aditiva:
 [[ 5.+4.j  3.-2.j]
 [ 0.+1.j -4.+2.j]] 
 [[ 5.+4.j  3.-2.j]
 [ 0.+1.j -4.+2.j]] 

Inverso aditivo:
 [[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]] 

Identidad multiplicativa:
 [[ 5.+4.j  3.-2.j]
 [ 0.+1.j -4.+2.j]] 
 [[ 5.+4.j  3.-2.j]
 [ 0.+1.j -4.+2.j]] 

Multiplicación escalar:
 [[ 268.+116.j  108.-124.j]
 [  12. +44.j -152.+136.j]] 
 [[ 268.+116.j  108.-124.j]
 [  12. +44.j -152.+136.j]] 

Multiplicación escalar se distribuye sobre adicion:
 [[ 32.+14.j  -8.-16.j]
 [ 34.-12.j -32.+16.j]] 
 [[ 32.+14.j  -8.-16.j]
 [ 34.-12.j -32.+16.j]] 

Multi

# Operaciones con matrices cuadradas

In [4]:
Q = np.array([[4j, 8 - 1j, 6j], [2, -4 + 4j, 10 - 6j], [10 - 1j, -2 - 2j, 3]])
print(Q.shape)
print('Ejemplo: \n', Q, '\n')
print('Transpuesta: \n', Q.T, '\n')
print('Conjugada: \n', Q.conjugate(), '\n')
print('Adjunta: \n', np.matrix(Q).getH(), '\n\n', Q.T.conjugate(), '\n\n', Q.conjugate().T, '\n')

(3, 3)
Ejemplo: 
 [[ 0.+4.j  8.-1.j  0.+6.j]
 [ 2.+0.j -4.+4.j 10.-6.j]
 [10.-1.j -2.-2.j  3.+0.j]] 

Transpuesta: 
 [[ 0.+4.j  2.+0.j 10.-1.j]
 [ 8.-1.j -4.+4.j -2.-2.j]
 [ 0.+6.j 10.-6.j  3.+0.j]] 

Conjugada: 
 [[ 0.-4.j  8.+1.j  0.-6.j]
 [ 2.-0.j -4.-4.j 10.+6.j]
 [10.+1.j -2.+2.j  3.-0.j]] 

Adjunta: 
 [[ 0.-4.j  2.-0.j 10.+1.j]
 [ 8.+1.j -4.-4.j -2.+2.j]
 [ 0.-6.j 10.+6.j  3.-0.j]] 

 [[ 0.-4.j  2.-0.j 10.+1.j]
 [ 8.+1.j -4.-4.j -2.+2.j]
 [ 0.-6.j 10.+6.j  3.-0.j]] 

 [[ 0.-4.j  2.-0.j 10.+1.j]
 [ 8.+1.j -4.-4.j -2.+2.j]
 [ 0.-6.j 10.+6.j  3.-0.j]] 



# Multiplicacion de matrices

In [5]:
Q = np.array([[4j, 8 - 1j, 6j], [2, -4 + 4j, 10 - 6j], [10 - 1j, -2 - 2j, 3]])
R = np.array([[2j, 8 + 1j, 0], [2, -4 + 4j, 10 - 10j], [10 - 1j, -2 - 2j, 3]])

print('Multiplicacion no conmutativa: \n', np.matmul(Q, R), '\n', np.matmul(R, Q), '\n')
print('Multiplicacion con transpuestas: \n', np.matmul(Q, R).T, '\n', np.matmul(R.T, Q.T), '\n')
print('Multiplicacion con adjuntas: \n', np.matrix(np.matmul(Q, R)).getH(), '\n', np.matmul(np.matrix(R).getH(), np.matrix(Q).getH()), '\n')
#print('Conjugada: \n', Q.conjugate(), '\n')
#print('Adjunta: \n', np.matrix(Q).getH(), '\n\n', Q.T.conjugate(), '\n\n', Q.conjugate().T, '\n')

Multiplicacion no conmutativa: 
 [[ 14.+58.j -20.+56.j  70.-72.j]
 [ 86.-58.j -16.-38.j  30.+62.j]
 [ 28.+13.j  91. -4.j -31. +0.j]] 
 [[  8. +2.j -34.+44.j  74.-38.j]
 [ 82.-94.j -24.-34.j  14.+46.j]
 [ 30.+33.j  89.-24.j -17.+52.j]] 

Multiplicacion con transpuestas: 
 [[ 14.+58.j  86.-58.j  28.+13.j]
 [-20.+56.j -16.-38.j  91. -4.j]
 [ 70.-72.j  30.+62.j -31. +0.j]] 
 [[ 14.+58.j  86.-58.j  28.+13.j]
 [-20.+56.j -16.-38.j  91. -4.j]
 [ 70.-72.j  30.+62.j -31. +0.j]] 

Multiplicacion con adjuntas: 
 [[ 14.-58.j  86.+58.j  28.-13.j]
 [-20.-56.j -16.+38.j  91. +4.j]
 [ 70.+72.j  30.-62.j -31. -0.j]] 
 [[ 14.-58.j  86.+58.j  28.-13.j]
 [-20.-56.j -16.+38.j  91. +4.j]
 [ 70.+72.j  30.-62.j -31. +0.j]] 



# Isomorfismo entre complejos y reales

In [6]:
r1 = 4 
r2 = -5
mat_r = np.array([[r1, r2], [-r2, r1]])
c = 4 - 5j 

s_r = np.array([[-1, 7], [-7, -1]])

print('Sumar elemento: \n', c + (-1 + 7j), '\n', mat_r + s_r, '\n')
print('Elevar al cuadrado: \n', c ** 2, '\n', np.matmul(mat_r, mat_r), '\n')

#ADICION EN FUNCION LINEAL
elemento_a = 7
elemento_b = -2

elemento_c = -1
elemento_d = -2

mat_r1 = np.array([[elemento_a, elemento_b], [-1 * elemento_b, elemento_a]])
mat_r2 = np.array([[elemento_c, elemento_d], [-1 * elemento_d, elemento_c]])

c1 = elemento_a + 1j * elemento_b 
c2 = elemento_c + 1j * elemento_d 

escalar = 10

print('Suma de dos elementos: \n', c1 + c2, '\n', mat_r1 + mat_r2,  '\n')
print('Multiplicacion por escalar real: \n', c1 * escalar, '\n', escalar * mat_r1,  '\n')
print('Multiplicacion de dos elementos: \n', c1 * c2, '\n', np.matmul(mat_r1, mat_r2),  '\n')

Sumar elemento: 
 (3+2j) 
 [[ 3  2]
 [-2  3]] 

Elevar al cuadrado: 
 (-9-40j) 
 [[ -9 -40]
 [ 40  -9]] 

Suma de dos elementos: 
 (6-4j) 
 [[ 6 -4]
 [ 4  6]] 

Multiplicacion por escalar real: 
 (70-20j) 
 [[ 70 -20]
 [ 20  70]] 

Multiplicacion de dos elementos: 
 (-11-12j) 
 [[-11 -12]
 [ 12 -11]] 



# Hadamard Matrix

In [7]:
H = np.array([[1 / 2**0.5, 1 / 2**0.5], [1 / 2**0.5, -1 / 2**0.5]])

print('Hadamard matrix: \n', H, '\n')
print('Hadamard matrix ** 2: \n', H @ H, '\n')
print('Hadamard matrix ** 3: \n', H @ H @ H, '\n')

Hadamard matrix: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]] 

Hadamard matrix ** 2: 
 [[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]] 

Hadamard matrix ** 3: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]] 



# Espacio vectorial con Producto Interno

In [8]:
A = np.array([[1j, 4 - 2j], [6, 10j]])
B = np.array([[-3 + 2j, 5], [1j, 2j]])

print('Producto interno no degenerativo: \n', np.vdot(A, A), '\n')
print('Sesgo simetrico: \n', np.vdot(A, B), '\n', np.vdot(B, A).conjugate(), '\n')
print('Producto interno con definicion: \n', np.trace(np.matrix(A).getH() @ B), '\n')
print('Norma o longitud: \n', np.linalg.norm(A), '\n', np.linalg.norm(A) ** 2, '\n')
print('Distancia: \n', np.linalg.norm(A), np.linalg.norm(B), np.linalg.norm(A - B), np.linalg.norm(B - A), '\n')


Producto interno no degenerativo: 
 (157+0j) 

Sesgo simetrico: 
 (42+19j) 
 (42+19j) 

Producto interno con definicion: 
 (42+19j) 

Norma o longitud: 
 12.529964086141668 
 157.0 

Distancia: 
 12.529964086141668 6.557438524302 10.770329614269007 10.770329614269007 



# Eigenvalores y Eigenvectores

In [21]:
A = np.array([[1, -3, 3], [3, -5, 3], [6, -6, 4]])

e_val, e_vec = np.linalg.eig(A)

print('Eigenvalores: \n', e_val, '\n')
print('Eigenvectores: \n', e_vec, '\n')
print('Comprobacion 1: \n', e_val[0] * e_vec[0], A @ e_vec[0])
print('Comprobacion 1: \n', -2 * np.array([1, 1, 0]), A @ np.array([1, 1, 0]))

Eigenvalores: 
 [ 4. -2. -2.] 

Eigenvectores: 
 [[-0.40824829 -0.81034214  0.1932607 ]
 [-0.40824829 -0.31851537 -0.59038328]
 [-0.81649658  0.49182677 -0.78364398]] 

Comprobacion 1: 
 [-1.63299316 -3.24136856  0.77304281] [2.60256024 3.40674794 3.18560592]
Comprobacion 1: 
 [-2 -2  0] [-2 -2  0]


# Hermitianas y Unitarias

In [34]:
A = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
B = np.array([[5, 4 + 5j, 6 - 16j], [4 - 5j, 13, 7], [6 + 16j, 7, -2.1]])
C = np.array([[5, 0, 0], [0, 13, 0], [0, 0, -2.1]])
D = np.array([[np.cos(np.pi / 4), -np.sin(np.pi / 4), 0], 
              [np.sin(np.pi / 4), np.cos(np.pi / 4), 0], 
              [0, 0, 1]])

print('Matriz simetrica: ', '\n', A, '\n', A.T, '\n')
print('Matriz hermitiana: ', '\n', B, '\n', np.matrix(B).getH(), '\n')
print('Matriz diagonal: ', '\n', C, '\n')

e_val, e_vec = np.linalg.eigh(B)
print('Eigenvalores: \n', e_val, '\n')
print('Eigenvectores: \n', e_vec, '\n')
print('Ortogonalidad: ', np.vdot(e_vec[0], e_vec[1]), np.vdot(e_vec[0], e_vec[2]), np.vdot(e_vec[1], e_vec[2]), '\n')

D_adj = np.matrix(D).getH()
print('Matriz unitaria: \n', D, '\n', D_adj, '\n', D @ D_adj, '\n', D_adj @ D, '\n')

Matriz simetrica:  
 [[1 2 3]
 [2 4 5]
 [3 5 6]] 
 [[1 2 3]
 [2 4 5]
 [3 5 6]] 

Matriz hermitiana:  
 [[ 5.  +0.j  4.  +5.j  6. -16.j]
 [ 4.  -5.j 13.  +0.j  7.  +0.j]
 [ 6. +16.j  7.  +0.j -2.1 +0.j]] 
 [[ 5.  -0.j  4.  +5.j  6. -16.j]
 [ 4.  -5.j 13.  -0.j  7.  -0.j]
 [ 6. +16.j  7.  -0.j -2.1 -0.j]] 

Matriz diagonal:  
 [[ 5.   0.   0. ]
 [ 0.  13.   0. ]
 [ 0.   0.  -2.1]] 

Eigenvalores: 
 [-18.23072189  12.1869549   21.94376699] 

Eigenvectores: 
 [[-0.61004189+0.j         -0.45193547-0.j          0.65084808+0.j        ]
 [ 0.03021259-0.25842891j  0.73921839+0.30244296j  0.54161634-0.03221605j]
 [ 0.21380092+0.71724456j  0.17238914-0.35793959j  0.32009971+0.42372965j]] 

Ortogonalidad:  (1.437037535410667e-16+5.023797211367136e-17j) (1.5357465835512936e-18-1.2368380604324905e-16j) (-1.6653345369377348e-16-1.0061396160665481e-16j) 

Matriz unitaria: 
 [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]] 
 [[ 0.7071

# Tensores

In [46]:
A = np.array([3, 4, 7])
B = np.array([-1, 2])

C = np.array([[3 + 2j, 5 - 1j, 2j], [0, 12, 6 - 3j], [2, 4 + 4j, 9 + 3j]])
D = np.array([[1, 3 + 4j, 5 - 7j], [10 + 2j, 6, 2 + 5j], [0, 1, 2 + 9j]])

E = np.array([[3 + 2j, 5 - 1j], [0, 12]])
F = np.array([[1, 3 + 4j, 5 - 7j], [10 + 2j, 6, 2 + 5j], [0, 1, 2 + 9j]])

tens_1 = np.tensordot(C, D, axes=0)

print('Producto tensorial: ', '\n', np.tensordot(A, B, axes=0), '\n')
print('Producto tensorial: ', '\n', tens_1, '\n', tens_1.shape, '\n')
#print('Adjuntos: ', '\n', np.linalg.tensordot(E, F, axes=0), '\n')

Producto tensorial:  
 [[-3  6]
 [-4  8]
 [-7 14]] 

Producto tensorial:  
 [[[[  3.  +2.j   1. +18.j  29. -11.j]
   [ 26. +26.j  18. +12.j  -4. +19.j]
   [  0.  +0.j   3.  +2.j -12. +31.j]]

  [[  5.  -1.j  19. +17.j  18. -40.j]
   [ 52.  +0.j  30.  -6.j  15. +23.j]
   [  0.  +0.j   5.  -1.j  19. +43.j]]

  [[  0.  +2.j  -8.  +6.j  14. +10.j]
   [ -4. +20.j   0. +12.j -10.  +4.j]
   [  0.  +0.j   0.  +2.j -18.  +4.j]]]


 [[[  0.  +0.j   0.  +0.j   0.  +0.j]
   [  0.  +0.j   0.  +0.j   0.  +0.j]
   [  0.  +0.j   0.  +0.j   0.  +0.j]]

  [[ 12.  +0.j  36. +48.j  60. -84.j]
   [120. +24.j  72.  +0.j  24. +60.j]
   [  0.  +0.j  12.  +0.j  24.+108.j]]

  [[  6.  -3.j  30. +15.j   9. -57.j]
   [ 66. -18.j  36. -18.j  27. +24.j]
   [  0.  +0.j   6.  -3.j  39. +48.j]]]


 [[[  2.  +0.j   6.  +8.j  10. -14.j]
   [ 20.  +4.j  12.  +0.j   4. +10.j]
   [  0.  +0.j   2.  +0.j   4. +18.j]]

  [[  4.  +4.j  -4. +28.j  48.  -8.j]
   [ 32. +48.j  24. +24.j -12. +28.j]
   [  0.  +0.j   4.  +4.j -28. +